#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# keyboard setup
xset r rate 300 50 &
setxkbmap -option ctrl:nocaps -option altwin:swap_alt_win &
# display setup
xset s 480 dpms 600 600 600 &
# autostart
$HOME/.config/polybar/launch.sh &
1password --silent &
nitrogen --restore &

bspc monitor -d home web work dev org term

bspc config border_width         3
bspc config window_gap          6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc query -N -d ^1 | xargs -I node_id bspc node node_id -t floating
