#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
picom -b --fade-in-step=1 --fade-out-step=1 --fade-delta=0 &
# keyboard setup
xset r rate 300 50 &
setxkbmap -option ctrl:nocaps &
# display setup
xset s 480 dpms 600 600 600 &
xrandr --output eDP-1 --gamma 0.9:0.9:0.9 --brightness 1.1 &
# mouse setup
xinput set-prop 11 'libinput Accel Speed' -0.57 &
xinput set-prop 11 'libinput Horizontal Scroll Enabled' 0 &

# autostart
$HOME/.config/polybar/launch.sh &
1password --silent &
# nitrogen --restore &
# feh --bg-fill $HOME/wall.jpg &
hsetroot -solid "#0f4c81"

bspc monitor -d home web work dev org term

bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# bspc query -N -d ^1 | xargs -I node_id bspc node node_id -t floating
